config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  resources :call_records

  resources :users

  get 'static_pages/index'

  get 'static_pages/enter'

  get 'static_pages/view'

  get 'static_pages/search'

  root 'static_pages#index'

end

app/models/call_record.rb
class CallRecord < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :CallRecord
  attr_accessor :name, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/call_records_controller.rb
class CallRecordsController < ApplicationController
  before_action :set_call_record, only: [:show, :edit, :update, :destroy]

  # GET /call_records
  # GET /call_records.json
  def index
    @call_records = CallRecord.all
  end

  # GET /call_records/1
  # GET /call_records/1.json
  def show
  end

  # GET /call_records/new
  def new
    @call_record = CallRecord.new
  end

  # GET /call_records/1/edit
  def edit
  end

  # POST /call_records
  # POST /call_records.json
  def create
    @call_record = CallRecord.new(call_record_params)

    respond_to do |format|
      if @call_record.save
        format.html { redirect_to @call_record, notice: 'Call record was successfully created.' }
        format.json { render :show, status: :created, location: @call_record }
      else
        format.html { render :new }
        format.json { render json: @call_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /call_records/1
  # PATCH/PUT /call_records/1.json
  def update
    respond_to do |format|
      if @call_record.update(call_record_params)
        format.html { redirect_to @call_record, notice: 'Call record was successfully updated.' }
        format.json { render :show, status: :ok, location: @call_record }
      else
        format.html { render :edit }
        format.json { render json: @call_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /call_records/1
  # DELETE /call_records/1.json
  def destroy
    @call_record.destroy
    respond_to do |format|
      format.html { redirect_to call_records_url, notice: 'Call record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call_record
      @call_record = CallRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_record_params
      params.require(:call_record).permit(:content, :user_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def enter
  end

  def search
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/call_records_helper.rb
module CallRecordsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/call_records/_form.html.erb
<%= form_for(@call_record) do |f| %>
  <% if @call_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call_record.errors.count, "error") %> prohibited this call_record from being saved:</h2>

      <ul>
      <% @call_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/call_records/edit.html.erb
<h1>Editing Call Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @call_record %> |
<%= link_to 'Back', call_records_path %>

app/views/call_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Call Records</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @call_records.each do |call_record| %>
      <tr>
        <td><%= call_record.content %></td>
        <td><%= call_record.user_id %></td>
        <td><%= link_to 'Show', call_record %></td>
        <td><%= link_to 'Edit', edit_call_record_path(call_record) %></td>
        <td><%= link_to 'Destroy', call_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Submit new call', new_call_record_path %>

app/views/call_records/new.html.erb
<h1>New Call Record</h1>

<%= render 'form' %>

<%= link_to 'Back', call_records_path %>

app/views/call_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @call_record.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @call_record.user_id %>
</p>

<%= link_to 'Edit', edit_call_record_path(@call_record) %> |
<%= link_to 'Back', call_records_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Logbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <nav>
        <li><a href="/call_records/new">Submit new call</a></li>
        <li><a href="/call_records">View open calls</a></li>
        <li>Search Calls</li>
        <li>Other</li>
      </nav>



    </div>


<%= yield %>

</body>
</html>

app/views/static_pages/enter.html.erb
<h1>Enter new Call</h1>
    <form>
        <table>
            <tr><td>Name of Caller:</td> <td><input type="text"></td></tr>
            <tr><td> Caller Phone Number:</td><td><input type="text"></td></tr>
            <tr><td> Caller Location:</td><td><input type="text"></td></tr>
            <tr><td>Patient's Name:</td><td><input type="text"></td></tr>
            <tr><td>MRN:</td><td><input type="text"></td></tr>
            <tr><td>Visit Type:</td>
                <td>
                  <select>
                    <option>Inpatient</option>
                    <option>Outpatient</option>
                    <option>ER</option>
                    <option>Referred In</option>
                  </select>

            </tr>
            <tr><td>Patient Location:</td><td><input type="text"></td></tr>
            <tr><td>Call Started:</td><td></tr>
            <tr><td>Site:</td>
                <td>
                  <select>
                    <option>TGH</option>
                    <option>PMH</option>
                    <option>TWH</option>
                    <option>TRI</option>
                    <option>Sunnybrook</option>
                    <option>External</option>
                  </select>
                </tr>
            <tr><td>Type of Inquiry:</td>
                <td>
                  <select>
                    <option>Add-on</option>
                    <option>Critical</option>
                    <option>Other</option>
                    <option>Query</option>
                    <option>Reroute</option>
                    <option>Transfer</option>
                  </select>
                </tr>
            <tr><td>Call Route:</td>
                <td>
                  <select>
                    <option>Direct Call</option>
                    <option>Pager</option>
                    <option>Transfer</option>
                    <option>Voice Mail</option>
                  </select>
            </tr>
            <tr><td>Assigned to:</td><td></tr>
            <tr><td>Status:</td><td></tr>
            <tr><td>No. of calls</td>
                <td>
                  <select>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5+</option>
                  </select>

                </tr>


</form>
<!--

Description:

Resolution: -->

<!--Submit button-->

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Display open calls here</p>

app/views/static_pages/search.html.erb
<h1>StaticPages#search</h1>
<p>Find me in app/views/static_pages/search.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>